# docker-compose.yaml

version: '3.8'

services:
  # Next.js frontend service
  nextjs:
    build:
      context: ./nextjs    # Path to the Next.js folder
    ports:
      - "3000:3000"        # Map host port 3000 to container port 3000
    volumes:
      - ./nextjs:/src      # Map the nextjs folder to /src inside the container
      # This is to avoid conflicts between the host's node_modules and container's node_modules
      - /src/node_modules
    working_dir: /src      # Set the working directory inside the container
    command: npm run dev   # Command to start the Next.js server in development mode
    depends_on:
      - fastapi            # Ensure Next.js waits for FastAPI to start

  # PostgreSQL database service
  db:
    image: postgres:13         # Use the PostgreSQL 13 image
    ports:
      - "5432:5432"            # Map host port 5432 to container port 5432
    environment:
      POSTGRES_USER: temp      # Set the database user
      POSTGRES_PASSWORD: temp  # Set the database password
      POSTGRES_DB: advcompro   # Set the default database name
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist PostgreSQL data

  # FastAPI backend service
  fastapi:
    build:
      context: ./fastapi    # Path to the FastAPI folder
    ports:
      - "8000:8000"         # Map host port 8000 to container port 8000
    volumes:
      - ./fastapi:/src      # Map the fastapi folder to /src inside the container
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload  # Command to start FastAPI
    depends_on:
      - db                  # Ensure FastAPI waits for the database to start
    environment:
      DATABASE_URL: postgresql+asyncpg://temp:temp@db/advcompro  # Database URL for FastAPI

# Named volumes for data persistence
volumes:
  postgres_data:
